import { createSlice } from "@reduxjs/toolkit";

// Initial state for the expansion-related UI parts
const initialState = {
  bestScenarioExpanded: false,    // Controls whether the "Best Scenario" section is expanded
  contextWindowExpanded: false,   // Controls whether the context info window is visible
  moreVariablesExpanded: false,   // Controls whether the "More Variables" section is expanded
};

// Define the slice with name, initial state, and reducers
const expandSlice = createSlice({
  name: "expand",  // Slice name, used as prefix in action types
  initialState,
  reducers: {
    // Toggle the boolean state of bestScenarioExpanded
    toggleBestScenario(state) {
      state.bestScenarioExpanded = !state.bestScenarioExpanded;
    },

    // Toggle the boolean state of contextWindowExpanded
    toggleContextWindow(state) {
      state.contextWindowExpanded = !state.contextWindowExpanded;
    },

    // Toggle the boolean state of moreVariablesExpanded
    toggleMoreVariables(state) {
      state.moreVariablesExpanded = !state.moreVariablesExpanded;
    },
  },
});

// Export the action creators generated by createSlice for use in components
export const { toggleBestScenario, toggleContextWindow, toggleMoreVariables } = expandSlice.actions;

// Export the reducer to be added to the store
export default expandSlice.reducer;
